echo off
rem Run a sequence of experiments

rem Test baseline model on synthetic data 
python .\tools\test.py configs\catchmonitor\faster-rcnn_r50_fpn_1x_coco_mrvscotia_syn_baseline.py work_dirs\faster-rcnn_r50_fpn_1x_coco_mrvscotia_syn_baseline\epoch_100.pth --show-dir Exp110 --cfg-options test_dataloader.dataset.data_root="data/belt_data_synthetic/Experiment110/mrv_scotia/" test_dataloader.dataset.ann_file="val/annotation_coco.json" test_evaluator.ann_file="data/belt_data_synthetic/Experiment110/mrv_scotia/val/annotation_coco.json" > .\work_dirs\faster-rcnn_r50_fpn_1x_coco_mrvscotia_syn_baseline\exp110.txt
python .\tools\test.py configs\catchmonitor\faster-rcnn_r50_fpn_1x_coco_mrvscotia_syn_baseline.py work_dirs\faster-rcnn_r50_fpn_1x_coco_mrvscotia_syn_baseline\epoch_100.pth --show-dir Exp120 --cfg-options test_dataloader.dataset.data_root="data/belt_data_synthetic/Experiment120/mrv_scotia/" test_dataloader.dataset.ann_file="val/annotation_coco.json" test_evaluator.ann_file="data/belt_data_synthetic/Experiment120/mrv_scotia/val/annotation_coco.json" > .\work_dirs\faster-rcnn_r50_fpn_1x_coco_mrvscotia_syn_baseline\exp120.txt
python .\tools\test.py configs\catchmonitor\faster-rcnn_r50_fpn_1x_coco_mrvscotia_syn_baseline.py work_dirs\faster-rcnn_r50_fpn_1x_coco_mrvscotia_syn_baseline\epoch_100.pth --show-dir Exp130 --cfg-options test_dataloader.dataset.data_root="data/belt_data_synthetic/Experiment130/mrv_scotia/" test_dataloader.dataset.ann_file="val/annotation_coco.json" test_evaluator.ann_file="data/belt_data_synthetic/Experiment130/mrv_scotia/val/annotation_coco.json" > .\work_dirs\faster-rcnn_r50_fpn_1x_coco_mrvscotia_syn_baseline\exp130.txt
python .\tools\test.py configs\catchmonitor\faster-rcnn_r50_fpn_1x_coco_mrvscotia_syn_baseline.py work_dirs\faster-rcnn_r50_fpn_1x_coco_mrvscotia_syn_baseline\epoch_100.pth --show-dir Exp140 --cfg-options test_dataloader.dataset.data_root="data/belt_data_synthetic/Experiment140/mrv_scotia/" test_dataloader.dataset.ann_file="val/annotation_coco.json" test_evaluator.ann_file="data/belt_data_synthetic/Experiment140/mrv_scotia/val/annotation_coco.json" > .\work_dirs\faster-rcnn_r50_fpn_1x_coco_mrvscotia_syn_baseline\exp140.txt
python .\tools\test.py configs\catchmonitor\faster-rcnn_r50_fpn_1x_coco_mrvscotia_syn_baseline.py work_dirs\faster-rcnn_r50_fpn_1x_coco_mrvscotia_syn_baseline\epoch_100.pth --show-dir Exp150 --cfg-options test_dataloader.dataset.data_root="data/belt_data_synthetic/Experiment150/mrv_scotia/" test_dataloader.dataset.ann_file="val/annotation_coco.json" test_evaluator.ann_file="data/belt_data_synthetic/Experiment150/mrv_scotia/val/annotation_coco.json" > .\work_dirs\faster-rcnn_r50_fpn_1x_coco_mrvscotia_syn_baseline\exp150.txt
python .\tools\test.py configs\catchmonitor\faster-rcnn_r50_fpn_1x_coco_mrvscotia_syn_baseline.py work_dirs\faster-rcnn_r50_fpn_1x_coco_mrvscotia_syn_baseline\epoch_100.pth --show-dir Exp160 --cfg-options test_dataloader.dataset.data_root="data/belt_data_synthetic/Experiment160/mrv_scotia/" test_dataloader.dataset.ann_file="val/annotation_coco.json" test_evaluator.ann_file="data/belt_data_synthetic/Experiment160/mrv_scotia/val/annotation_coco.json" > .\work_dirs\faster-rcnn_r50_fpn_1x_coco_mrvscotia_syn_baseline\exp160.txt

rem Test IoU-Net model on synthetic data 
python .\tools\test.py configs\catchmonitor\faster-rcnn_r50_fpn_1x_coco_mrvscotia_iou-net.py work_dirs\faster-rcnn_r50_fpn_1x_coco_mrvscotia_syn_iou-net\epoch_100.pth --show-dir Exp110 --cfg-options test_dataloader.dataset.data_root="data/belt_data_synthetic/Experiment110/mrv_scotia/" test_dataloader.dataset.ann_file="val/annotation_coco.json" test_evaluator.ann_file="data/belt_data_synthetic/Experiment110/mrv_scotia/val/annotation_coco.json" > .\work_dirs\faster-rcnn_r50_fpn_1x_coco_mrvscotia_syn_iou-net\exp110.txt
python .\tools\test.py configs\catchmonitor\faster-rcnn_r50_fpn_1x_coco_mrvscotia_iou-net.py work_dirs\faster-rcnn_r50_fpn_1x_coco_mrvscotia_syn_iou-net\epoch_100.pth --show-dir Exp120 --cfg-options test_dataloader.dataset.data_root="data/belt_data_synthetic/Experiment120/mrv_scotia/" test_dataloader.dataset.ann_file="val/annotation_coco.json" test_evaluator.ann_file="data/belt_data_synthetic/Experiment120/mrv_scotia/val/annotation_coco.json" > .\work_dirs\faster-rcnn_r50_fpn_1x_coco_mrvscotia_syn_iou-net\exp120.txt
python .\tools\test.py configs\catchmonitor\faster-rcnn_r50_fpn_1x_coco_mrvscotia_iou-net.py work_dirs\faster-rcnn_r50_fpn_1x_coco_mrvscotia_syn_iou-net\epoch_100.pth --show-dir Exp130 --cfg-options test_dataloader.dataset.data_root="data/belt_data_synthetic/Experiment130/mrv_scotia/" test_dataloader.dataset.ann_file="val/annotation_coco.json" test_evaluator.ann_file="data/belt_data_synthetic/Experiment130/mrv_scotia/val/annotation_coco.json" > .\work_dirs\faster-rcnn_r50_fpn_1x_coco_mrvscotia_syn_iou-net\exp130.txt
python .\tools\test.py configs\catchmonitor\faster-rcnn_r50_fpn_1x_coco_mrvscotia_iou-net.py work_dirs\faster-rcnn_r50_fpn_1x_coco_mrvscotia_syn_iou-net\epoch_100.pth --show-dir Exp140 --cfg-options test_dataloader.dataset.data_root="data/belt_data_synthetic/Experiment140/mrv_scotia/" test_dataloader.dataset.ann_file="val/annotation_coco.json" test_evaluator.ann_file="data/belt_data_synthetic/Experiment140/mrv_scotia/val/annotation_coco.json" > .\work_dirs\faster-rcnn_r50_fpn_1x_coco_mrvscotia_syn_iou-net\exp140.txt
python .\tools\test.py configs\catchmonitor\faster-rcnn_r50_fpn_1x_coco_mrvscotia_iou-net.py work_dirs\faster-rcnn_r50_fpn_1x_coco_mrvscotia_syn_iou-net\epoch_100.pth --show-dir Exp150 --cfg-options test_dataloader.dataset.data_root="data/belt_data_synthetic/Experiment150/mrv_scotia/" test_dataloader.dataset.ann_file="val/annotation_coco.json" test_evaluator.ann_file="data/belt_data_synthetic/Experiment150/mrv_scotia/val/annotation_coco.json" > .\work_dirs\faster-rcnn_r50_fpn_1x_coco_mrvscotia_syn_iou-net\exp150.txt
python .\tools\test.py configs\catchmonitor\faster-rcnn_r50_fpn_1x_coco_mrvscotia_iou-net.py work_dirs\faster-rcnn_r50_fpn_1x_coco_mrvscotia_syn_iou-net\epoch_100.pth --show-dir Exp160 --cfg-options test_dataloader.dataset.data_root="data/belt_data_synthetic/Experiment160/mrv_scotia/" test_dataloader.dataset.ann_file="val/annotation_coco.json" test_evaluator.ann_file="data/belt_data_synthetic/Experiment160/mrv_scotia/val/annotation_coco.json" > .\work_dirs\faster-rcnn_r50_fpn_1x_coco_mrvscotia_syn_iou-net\exp160.txt
